###########################################################
# Dockerfile that builds a CSGO Gameserver
###########################################################
FROM github.com/sbuggay/srcds-docker

RUN wget -qO- https://github.com/splewis/get5/releases/download/0.7.1/get5_0.7.1.zip -O get5.zip \
    unzip get5.zip \
    rm get5.zip 
